dddns/urls.py
from django.conf.urls import url

from . import views

app_name = 'dddns'
urlpatterns = [
    url(r'^update$', views.update, name='update'),
    url(r'^info$', views.authinfo, name='authinfo'),
    url(r'^refresh$', views.refresh, name='refresh'),
    url(r'^status$', views.status, name='status'),
    url(r'^remove$', views.remove, name='remove'),
    url(r'^enroll$', views.enroll, name='enroll'),
    url(r'^$', views.status),
    url(r'^getip$', views.getip, name='getip'),
]

dddns/templates/auth-empty.html
<form method="POST" action="{% url 'dddns:authinfo' %}">
<p>
  Authorization Code: <input type="text" name="authcode" autofocus /> <input type="submit" />
</p>
</form>
<p>Other actions:
  <ul>
    <li>
      <a href="{% url 'dddns:enroll' %}">use an invite code</a>
    </li>
    <li>
      <a href="{% url 'dddns:status' %}">system status</a>
    </li>
  </ul>
</p>

dddns/templates/auth.html
<h1>Dynamic DNS updates for  <tt>{{ auth.name }}.{{ auth.domain.domain }}</tt></h1>
<p>Please <strong>save the authorization code!</strong>  Once you have left
  this page, there will be no record left of your authorization code.
</p>
<p>
  Your Authorization Code is: <div class="authcode">{{ auth.cleartext }}</div>
</p>
<p><tt>{{ auth.name }}.{{ auth.domain.domain }}</tt>
  {% if auth.ip %}currently points to <tt>{{ auth.ip }}</tt>{% else %}is currently unset{% endif %}.
</p>
<dl>
  <dt>Information</dt>
  <dd>
    You can retrieve the information about the current Authorization code at:
      <tt><a href="{% url 'dddns:authinfo' %}">https://{{ request.get_host }}{% url 'dddns:authinfo' %}</a></tt>
  </dd>
  <dt>Updating</dt>
  <dd>
    <p>
      If you know your own public IP address is {% if request.META.REMOTE_ADDR %}{{ request.META.REMOTE_ADDR }}{% else %}{{ 192.2.0.26 }}{% endif %}, then
      you can <tt>POST</tt> to
      <span class="posturl">https://{{ request.get_host }}{% url 'dddns:update' %}</span>
      with the following data:
      <div class="postdata">authcode={{ auth.cleartext }}&amp;ip={% if request.META.REMOTE_ADDR %}{{ request.META.REMOTE_ADDR }}{% else %}{{ 192.2.0.26 }}{% endif %}</div>
    </p>
    <p>
      An example with <tt>wget</tt> in the shell looks like this:
      <pre>
        wget -O- -q '--post-data=authcode={{ auth.cleartext }}&amp;ip={% if request.META.REMOTE_ADDR %}{{ request.META.REMOTE_ADDR }}{% else %}{{ 192.2.0.26 }}{% endif %}' 'https://{{ request.get_host }}{% url 'dddns:update' %}'
      </pre>
    </p>
    <p>
        If you don't know your IP address, you can leave it off, using <tt>POST</tt> data like this:
        <div class="postdata">authcode={{ auth.cleartext }}</div>
        And the server will guess your IP address using the same techniques it uses
        <a href="{% url 'dddns:getip' %}">to report your current IP</a>.
    </p>
    <p>
      An example with <tt>wget</tt> in the shell looks like this:
      <pre>
        wget -O- -q '--post-data=authcode={{ auth.cleartext }}' 'https://{{ request.get_host }}{% url 'dddns:update' %}'
      </pre>
    </p>
  </dd>
  <dt>Clearing</dt>
  <dd>
    <p>
      You can clear the IP address with a <tt>POST</tt>
      to <span class="posturl">https:{{ request.get_host }}{% url 'dddns:remove' %}</span>
      with the following data:
      <div class="postdata">authcode={{ auth.cleartext }}</div>
    </p>
  </dd>
  <dt>Refresh</dt>
  <dd>
    If you want to change this authorization code (e.g. if you're concerned that someone else has a copy of it), you can do so at:
 <tt><a href="{% url 'dddns:refresh' %}">https:{{ request.get_host }}{% url 'dddns:refresh' %}</a></tt>.

    </dd>
</dl>

dddns/templates/enroll-empty.html
<form method="POST" action="{% url 'dddns:enroll' %}">
  <p>Invite code: <input type="text" name="invite" autofocus /><input type="submit" /></p>
</form>
<p>Other actions:
  <ul>
    <li>
      <a href="{% url 'dddns:authinfo' %}">look up information about an authorization code</a>
    </li>
    <li>
      <a href="{% url 'dddns:status' %}">system status</a>
    </li>
  </ul>
</p>

dddns/templates/enroll.html
<form method="POST" action="{% url 'dddns:enroll' %}">
  <h1>Enroll a name in the <tt>{{ invite.domain.domain }}</tt> zone</h1>
  <p>Dynamic DNS registration</p>
  <input type="hidden" name="invite" value="{{ invite.cleartext }}" />
  <p>Please use only letters, numbers, hyphens, and underscores.</p>
  <p><tt><input type="text" name="name" autofocus />.{{ invite.domain.domain }}</tt></p>
  <p><input type="submit" /></p>
</form>

dddns/templates/refresh-empty.html
<form method="POST" action="{% url 'dddns:refresh' %}">
  <p>Refresh Authorization code: <input type="text" name="authcode" autofocus />
    <input type="submit" /></p>
</form>

dddns/templates/refresh.html
<form method="POST" action="{% url 'dddns:refresh' %}">
  <p>Are you sure you want to refresh the authorization code
  for <tt>{{ auth.name }}.{{ auth.domain.domain }}</tt>?  Doing so
  will invalidate the existing authorization code!
  <input type="hidden" name="authcode" value="{{ auth.cleartext }}" />
  <input type="hidden" name="ok" value="yes" />
  </p>
  <p><input type="submit" value="Yes, refresh!"/></p>
</form>

dddns/templates/status.html
<h1>Status of dynamic DNS updates</h1>
{% if domains %}
<dl>
  {% for domain in domains %}
  <dt><tt>{{ domain.domain }}</tt></dt>
  <dd>{{ domain.publication_status }}</dd>
  {% endfor %}
</dl>
{% else %}
No public DNS domains managed by this server.
{% endif %}
<p>Other actions:
  <ul>
    <li>
      <a href="{% url 'dddns:authinfo' %}">look up information about an authorization code</a>
    </li>
    <li>
      <a href="{% url 'dddns:enroll' %}">use an invite code</a>
    </li>
  </ul>
</p>